### PR TITLE
Update packages to current versions

### PR DESCRIPTION
**Pull request by sfmskywalker**

### CODE REVIEW

**Comment by joakimjm** [comment]
The myget build fails from the .net 5 update of the test project. That's why my initial thought was to revert the PR. 

A superficial googling didn't turn up anything to guide me to make myget build .net 5 projects, so I'll look more thoroughly again tomorrow morning.

Unless you have any suggestions or want to downgrade the test project again?

**Comment by sfmskywalker** [comment]
What build provider are you using? I know for example with AppVeyor, you need to select Visual Studio 2019 (Preview) in order to build .NET 5 projects.

**Comment by joakimjm** [comment]
I'm just using myget's own build service, that's part of open source subscription, it worked well and out of the box for this project until now 😅  The tradeoff I suppose is that I can't seem to find any flexibility in _how_ it builds stuff.

**Comment by sfmskywalker** [comment]
I see why: According to [this list](https://docs.myget.org/docs/reference/build-services#Supported_project_types_and_SDK), their build servers don't support .NET 5 yet 😅 

It's no biggie - I'll just include your project's source code directly for the time being.

**Pull request merged**
